steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/octus-backend:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/octus-backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'octus-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/octus-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'VISION_GEMINI_API_KEY=$$VISION_GEMINI_API_KEY,NLP_GEMINI_API_KEY=$$NLP_GEMINI_API_KEY'
    secretEnv: ['VISION_GEMINI_API_KEY', 'NLP_GEMINI_API_KEY']

images:
  - 'gcr.io/$PROJECT_ID/octus-backend:$COMMIT_SHA'

# Configure secrets from Secret Manager
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/vision-gemini-api-key/versions/latest
    env: 'VISION_GEMINI_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/nlp-gemini-api-key/versions/latest
    env: 'NLP_GEMINI_API_KEY'

options:
  logging: CLOUD_LOGGING_ONLY
